### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by thelistmaker** [tomascardososerra/fallback-chatgpt3-skill#1]
INFO - building SkillEntry objects for all skills
INFO - Downloading skill: https://github.com/tomascardososerra/fallback-chatgpt3-skill
INFO - Reading from manifest.yml
WARNING - Invalid value type manifest.yml for fallback-chatgpt3-skill: <class 'list'>
INFO - Problem performing action. Restoring skill to previous state...
INFO - invalidating skills cache
SkillRequirementsException: 'list' object has no attribute 'get'

**Comment by tomascardososerra** [comment]
removed manifest file. It wasn't needed anyway. Thanks!
